# Generated by Django 4.1.4 on 2023-06-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_board', '0002_author_category_comment_post_postcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
