# Generated by Django 4.1.4 on 2023-06-08 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_board', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentRating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postRating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
