# Generated by Django 4.1.4 on 2023-06-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_board', '0004_remove_comment_commentrating_remove_post_postrating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postCategory',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
