# Generated by Django 4.1.4 on 2023-06-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_board', '0006_post_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('Decline', 'Decline'), ('Approved', 'Approved')], default='Waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
