# Generated by Django 4.1.4 on 2023-06-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_board', '0007_comment_status_alter_post_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('Decline', 'Decline'), ('Approved', 'Approved'), ('Waiting', 'Waiting')], default='Waiting', max_length=20),
        ),
    ]
