# Generated by Django 4.1.4 on 2023-06-13 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_board', '0008_remove_comment_id_comment_commentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_board.category'),
        ),
    ]
