# Generated by Django 4.1.4 on 2023-01-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
    ]
