# Generated by Django 4.1.4 on 2023-01-29 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsPortal', '0007_category_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='Subscription',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
